/**
 * The Grades 2 to 6 discrete mathematics line.
 *
 * GENERATED. Do not edit by hand. Run brand/mksite.py in the curriculum
 * repository, which reads every field below out of the books themselves: the
 * weeks and their subtitles from each book's source, the standard codes and
 * page count from the built PDF's text layer, and the assertion count by
 * running that book's verify.py. Editing this file instead of the book is how
 * the site starts describing something that is not there.
 */

export type MathWeek = { n: number; strand: string; title: string; sub: string };

export type MathBook = {
  slug: string;
  grade: number;
  title: string;
  /** The mathematical move this year teaches. */
  move: string;
  moveLine: string;
  /** The thing the student builds across the year. Grade 2 has none. */
  artifact: string;
  artifactLine: string;
  lede: string;
  strands: string[];
  standards: string[];
  weeks: MathWeek[];
  pages: number;
  /** Answers in the teacher guide recomputed from the problems by verify.py. */
  checks: number;
  workbook: string;
  guide: string;
};

export const MATH_LINE: MathBook[] = [
  {
    slug: 'grade-1', grade: 1, title: 'What Goes Together',
    move: 'Sort it',
    moveLine: 'Things go together for a reason, and you can say the reason.',
    artifact: '',
    artifactLine: '',
    lede: 'A full year of sorting, matching and patterns, for six-year-olds. Every week hands the child a rule and asks them to use it, because holding a rule in your head while you work is the step underneath everything else in this line. The page carries one sentence and a picture, and the picture is the task.',
    strands: ['Dots & Lines', 'Matching', 'Numbers & Tens', 'Order & Time', 'Patterns', 'Pictures & Data', 'Shape & Space', 'Sorting & Rules', 'Steps & Paths', 'Ways of Counting'],
    standards: ['1.G.1', '1.G.2', '1.G.3', '1.MD.1', '1.MD.2', '1.MD.3', '1.MD.4', '1.NBT.1', '1.NBT.2', '1.NBT.3', '1.NBT.5', '1.OA.1', '1.OA.5', '1.OA.6', '1.OA.8'],
    pages: 77, checks: 147,
    workbook: '/downloads/what-goes-together-grade1.pdf',
    guide: '/downloads/what-goes-together-grade1-teacher-guide.html',
    weeks: [
      { n: 1, strand: 'Sorting & Rules', title: 'One Pile or the Other', sub: 'The rule is given. Every object goes in exactly one pile, and none is left over.' },
      { n: 2, strand: 'Sorting & Rules', title: 'What Is the Same?', sub: 'Naming a shared attribute out loud. The answer is a sentence, not a word.' },
      { n: 3, strand: 'Sorting & Rules', title: 'What Is Different?', sub: 'The same pairs as last week, asked the other way. Same and different are one skill.' },
      { n: 4, strand: 'Sorting & Rules', title: 'Does It Belong?', sub: 'Applying a stated rule to a new object. Yes or no, with a reason.' },
      { n: 5, strand: 'Sorting & Rules', title: 'Sort It Two Ways', sub: 'The same objects, a second rule, and different piles. Sorting is a choice.' },
      { n: 6, strand: 'Matching', title: 'One for Each', sub: 'One-to-one matching. Enough or not enough, decided without counting either row.' },
      { n: 7, strand: 'Matching', title: 'More, Fewer, or Same', sub: 'Comparing two sets by pairing them off, not by counting them (1.NBT.3).' },
      { n: 8, strand: 'Matching', title: 'Which Row Ran Out?', sub: 'Three sets put in order by pairing them against each other, none of them counted.' },
      { n: 9, strand: 'Patterns', title: 'What Comes Next?', sub: 'Repeating patterns, AB and ABB. The child continues the strip.' },
      { n: 10, strand: 'Patterns', title: 'Find the Part That Repeats', sub: 'Naming the unit of a repeating pattern, which is the thing that makes it a pattern.' },
      { n: 11, strand: 'Patterns', title: 'It Grows', sub: 'A growing pattern, not a repeating one. Each stage is bigger than the last.' },
      { n: 12, strand: 'Sorting & Rules', title: 'Sorting Fair', sub: 'Review of weeks 1 to 11. Every kind of question the year has asked so far.' },
      { n: 13, strand: 'Order & Time', title: 'Line Them Up', sub: 'Three objects in order by length (1.MD.1). Compared directly, never measured.' },
      { n: 14, strand: 'Order & Time', title: 'Longer Than the Pencil', sub: 'Indirect comparison (1.MD.2). Two things compared using a third that touches both.' },
      { n: 15, strand: 'Order & Time', title: 'How Many Paper Clips?', sub: 'Length as a row of same-size units laid end to end, with no gaps (1.MD.2).' },
      { n: 16, strand: 'Shape & Space', title: 'Sort the Shapes', sub: 'Shapes into piles by a rule the page states (1.G.1). The first shape week.' },
      { n: 17, strand: 'Shape & Space', title: 'What Makes It a Triangle?', sub: 'Defining and non-defining attributes (1.G.1). Three sides matters. Color does not.' },
      { n: 18, strand: 'Shape & Space', title: 'Two Shapes Make One', sub: 'Composing shapes (1.G.2). Two pieces put together and the whole named.' },
      { n: 19, strand: 'Shape & Space', title: 'Cut It Fair', sub: 'Halves and fourths by folding (1.G.3). Equal parts, decided by matching them up.' },
      { n: 20, strand: 'Dots & Lines', title: 'Around the Table', sub: 'A picture of who is next to who. Adjacency, drawn, and never named.' },
      { n: 21, strand: 'Dots & Lines', title: 'Everybody Waves', sub: 'Three friends, every wave drawn once. The handshake problem at its smallest.' },
      { n: 22, strand: 'Dots & Lines', title: 'Do Not Touch the Same Color', sub: 'Coloring so no two touching parts match. The rule is checked, never minimized.' },
      { n: 23, strand: 'Pictures & Data', title: 'Three Buckets', sub: 'Sorting into three categories and drawing what you found (1.MD.4).' },
      { n: 24, strand: 'Pictures & Data', title: 'Which Bucket Has More?', sub: 'Reading a picture graph back and comparing its bars (1.MD.4).' },
      { n: 25, strand: 'Steps & Paths', title: 'Getting There', sub: 'Any path from the start to the flag on a small grid, drawn by the child.' },
      { n: 26, strand: 'Steps & Paths', title: 'The Short Way', sub: 'Two drawn paths, each one counted, and the shorter one named (1.OA.1).' },
      { n: 27, strand: 'Steps & Paths', title: 'Follow the Arrows', sub: 'Three arrows executed in order, and the landing square marked.' },
      { n: 28, strand: 'Steps & Paths', title: 'Write the Arrows', sub: 'The reverse of last week: the start and the end are given, the arrows are not.' },
      { n: 29, strand: 'Numbers & Tens', title: 'A Ten and Some More', sub: 'A teen number is one full ten and some ones (1.NBT.2). Seen, not told.' },
      { n: 30, strand: 'Numbers & Tens', title: 'Ten More, Ten Less', sub: 'One row down is ten more, one row up is ten less (1.NBT.5).' },
      { n: 31, strand: 'Numbers & Tens', title: 'Rows of Ten', sub: 'Why the chart\'s columns end in the same digit, and what that says about ten (1.NBT.1).' },
      { n: 32, strand: 'Ways of Counting', title: 'Every Way to Make 6', sub: 'All the number pairs that make 6, listed in order so none is missed (1.OA.6).' },
      { n: 33, strand: 'Ways of Counting', title: 'Two Hats, Two Scarves', sub: 'Every outfit, drawn. There are four, and drawing them is the whole method.' },
      { n: 34, strand: 'Ways of Counting', title: 'Three Friends, Two Chairs', sub: 'Every pair from three, drawn. There are three, and order does not matter.' },
      { n: 35, strand: 'Order & Time', title: 'First, Next, Last', sub: 'Putting a day in order, and reading a clock on the hour (1.MD.3).' },
      { n: 36, strand: 'Sorting & Rules', title: 'The Last Sort', sub: 'Everything once more, and a look at what Grade 2 does with all of it.' },
    ],
  },
  {
    slug: 'grade-2', grade: 2, title: 'Things Worth Noticing',
    move: 'See it',
    moveLine: 'These objects exist, and they are interesting.',
    artifact: '',
    artifactLine: '',
    lede: 'A full year of maps, robots, secret codes and bridges, for seven-year-olds. Discrete mathematics needs almost no computational fluency, which is exactly why it works as enrichment. A student still shaky on regrouping can reason beautifully about a map coloring, and be asked to prove it.',
    strands: ['Algorithms & Codes', 'Counting Carefully', 'Data & Graphs', 'Maps & Colors', 'Measuring & Comparing', 'Money & Time', 'Number Structure', 'Paths & Routes', 'Shapes & Parts', 'Sorting & Logic'],
    standards: ['2.G.1', '2.G.2', '2.G.3', '2.MD.1', '2.MD.4', '2.MD.5', '2.MD.6', '2.MD.7', '2.MD.8', '2.MD.10', '2.NBT.1', '2.NBT.2', '2.NBT.4', '2.NBT.5', '2.NBT.7', '2.OA.1', '2.OA.2', '2.OA.3', '2.OA.4'],
    pages: 77, checks: 0,
    workbook: '/downloads/things-worth-noticing-grade2.pdf',
    guide: '/downloads/things-worth-noticing-grade2-teacher-guide.html',
    weeks: [
      { n: 1, strand: 'Sorting & Logic', title: 'What’s My Rule?', sub: 'Every group has a rule. Your job is to find it.' },
      { n: 2, strand: 'Sorting & Logic', title: 'Two Circles, One Middle', sub: 'Where two groups overlap.' },
      { n: 3, strand: 'Number Structure', title: 'Pair Them Up', sub: 'Even and odd, by pairing, not by memorizing.' },
      { n: 4, strand: 'Sorting & Logic', title: 'Always, Sometimes, Never', sub: 'Mathematicians do not just answer. They prove.' },
      { n: 5, strand: 'Number Structure', title: 'How Computers Count', sub: 'Two symbols, 0 and 1, are enough for every number.' },
      { n: 6, strand: 'Number Structure', title: 'Number Machines', sub: 'Feed a number in. A rule changes it. What comes out?' },
      { n: 7, strand: 'Number Structure', title: 'Put Them in Order', sub: 'Two ways to sort, and one is less work.' },
      { n: 8, strand: 'Sorting & Logic', title: 'Twenty Questions', sub: 'The fastest way to find a hidden number.' },
      { n: 9, strand: 'Paths & Routes', title: 'The Shortest Way to the Gold', sub: 'The fastest route is almost never the straightest.' },
      { n: 10, strand: 'Number Structure', title: 'Magic Squares', sub: 'Every row, every column, every diagonal, the same total.' },
      { n: 11, strand: 'Number Structure', title: 'Balance Puzzles', sub: 'Whatever one side weighs, the other side weighs too.' },
      { n: 12, strand: 'Counting Carefully', title: 'The Handshake Problem', sub: 'Everyone shakes hands once. How many handshakes?' },
      { n: 13, strand: 'Sorting & Logic', title: 'Detective Week', sub: 'Everything from the first twelve weeks, in one case file.' },
      { n: 14, strand: 'Measuring & Comparing', title: 'Sorting by Length', sub: 'The same method as Week 7, on something that is not a number.' },
      { n: 15, strand: 'Counting Carefully', title: 'Covering a Strip', sub: 'Two tile shapes. Surprisingly many ways.' },
      { n: 16, strand: 'Measuring & Comparing', title: 'Two Ways Across the Park', sub: 'Adding lengths to compare whole routes.' },
      { n: 17, strand: 'Maps & Colors', title: 'Color the Kingdom', sub: 'Neighbors must never match.' },
      { n: 18, strand: 'Maps & Colors', title: 'When Three Colors Is Not Enough', sub: 'A puzzle that took mathematicians 124 years.' },
      { n: 19, strand: 'Money & Time', title: 'How Many Ways to Make 15¢?', sub: 'Counting every answer without missing one.' },
      { n: 20, strand: 'Money & Time', title: 'The Fewest Coins', sub: 'A rule so simple a machine could follow it. Usually.' },
      { n: 21, strand: 'Money & Time', title: 'Clock Arithmetic', sub: 'On a clock, numbers wrap around.' },
      { n: 22, strand: 'Money & Time', title: 'Getting Ready for the Party', sub: 'Some jobs have to wait for others.' },
      { n: 23, strand: 'Data & Graphs', title: 'Dots and Lines', sub: 'A picture of who is connected to whom.' },
      { n: 24, strand: 'Data & Graphs', title: 'Who Wins the Tournament?', sub: 'Counting games without drawing every one.' },
      { n: 25, strand: 'Sorting & Logic', title: 'Puzzle Fair', sub: 'A little of everything from Weeks 14 to 24.' },
      { n: 26, strand: 'Paths & Routes', title: 'Trace It Without Lifting', sub: 'An old puzzle with a beautiful rule hiding inside.' },
      { n: 27, strand: 'Paths & Routes', title: 'The Bridges of the Old City', sub: 'A walk that was never possible, and the proof.' },
      { n: 28, strand: 'Paths & Routes', title: 'Connecting the Towns', sub: 'Every town joined, for the smallest possible cost.' },
      { n: 29, strand: 'Counting Carefully', title: 'Counting Routes', sub: 'How many ways to walk to school?' },
      { n: 30, strand: 'Shapes & Parts', title: 'Guess My Shape', sub: 'The Week 8 game, played with shapes.' },
      { n: 31, strand: 'Shapes & Parts', title: 'Cutting Fair Shares', sub: 'Equal parts do not have to look the same.' },
      { n: 32, strand: 'Shapes & Parts', title: 'Filling a Rectangle', sub: 'Rows and columns give the same total.' },
      { n: 33, strand: 'Counting Carefully', title: 'The Ice Cream Shop', sub: 'Counting every choice, without missing one.' },
      { n: 34, strand: 'Counting Carefully', title: 'Choice Trees', sub: 'The same counting, drawn as branches.' },
      { n: 35, strand: 'Algorithms & Codes', title: 'Program the Robot', sub: 'Instructions precise enough for a machine to follow.' },
      { n: 36, strand: 'Algorithms & Codes', title: 'Secret Codes', sub: 'The last week. Everything you learned, put to work.' },
    ],
  },
  {
    slug: 'grade-3', grade: 3, title: 'Count Every Way',
    move: 'Count it',
    moveLine: 'There is a system, and a reason you missed nothing.',
    artifact: 'The Counting Book',
    artifactLine: 'One page per counting method, each written in the student\'s own words with a worked example they chose. Twenty-four pages by week 36.',
    lede: 'Counting without listing everything, and knowing nothing was skipped. The year moves from listing in a fixed order, through the product rule and arrangements, to Pascal\'s triangle built by hand. Every method the student meets goes into a book they write themselves.',
    strands: ['Data', 'Dots & Lines', 'Fractions', 'Logic & Proof', 'Number Structure', 'Shape & Space', 'Steps & Rules', 'Ways of Counting'],
    standards: ['3.MD.1', '3.MD.3', '3.MD.6', '3.MD.7', '3.MD.8', '3.NBT.1', '3.NBT.2', '3.NF.1', '3.NF.3', '3.OA.1', '3.OA.2', '3.OA.3', '3.OA.4', '3.OA.5', '3.OA.6', '3.OA.7', '3.OA.8', '3.OA.9'],
    pages: 77, checks: 322,
    workbook: '/downloads/count-every-way-grade3.pdf',
    guide: '/downloads/count-every-way-grade3-teacher-guide.html',
    weeks: [
      { n: 1, strand: 'Ways of Counting', title: 'In Order, Every Time', sub: 'There is a way to list things so that nothing gets skipped.' },
      { n: 2, strand: 'Logic & Proof', title: 'Did I Miss Any?', sub: 'A list is not finished just because you stopped writing.' },
      { n: 3, strand: 'Ways of Counting', title: 'Two Stages', sub: 'When two choices come one after the other, you multiply.' },
      { n: 4, strand: 'Ways of Counting', title: 'Rows and Columns Count', sub: 'An array is not a picture of a count. It is the count.' },
      { n: 5, strand: 'Ways of Counting', title: 'Three Stages, One Tree', sub: 'Two stages you can hold in your head. Three, you draw.' },
      { n: 6, strand: 'Ways of Counting', title: 'Order Matters', sub: 'Gold, silver and bronze are not the same as just three winners.' },
      { n: 7, strand: 'Ways of Counting', title: 'Order Does Not Matter', sub: 'Picking a team is not the same as handing out medals.' },
      { n: 8, strand: 'Ways of Counting', title: 'Handshakes, Bigger', sub: 'Everybody shakes hands with everybody, once. Now do it for a hundred people.' },
      { n: 9, strand: 'Dots & Lines', title: 'Dots, Lines and Degree', sub: 'How many lines meet at a dot, and what that number gives away.' },
      { n: 10, strand: 'Logic & Proof', title: 'Pigeons and Holes', sub: 'Sometimes you can be sure without looking.' },
      { n: 11, strand: 'Steps & Rules', title: 'Sorting Your Hand', sub: 'Two people can both sort correctly and one can still do far less work.' },
      { n: 12, strand: 'Steps & Rules', title: 'Splitting the Search', sub: 'Guessing one at a time is the slowest possible plan.' },
      { n: 13, strand: 'Logic & Proof', title: 'Case Files', sub: 'One case file. Everything from the first twelve weeks is in here somewhere.' },
      { n: 14, strand: 'Shape & Space', title: 'Cutting a Rectangle', sub: 'Area is an array that forgot it was an array.' },
      { n: 15, strand: 'Shape & Space', title: 'Same Area, Different Shape', sub: 'Twelve squares can be laid out several ways, and the fence changes every time.' },
      { n: 16, strand: 'Shape & Space', title: 'Same Perimeter, Different Area', sub: 'Now hold the fence still and see what happens to the ground.' },
      { n: 17, strand: 'Ways of Counting', title: 'Rectangles Inside a Grid', sub: 'How many rectangles are hiding in a grid? More than you think.' },
      { n: 18, strand: 'Ways of Counting', title: 'Factor Pairs', sub: 'Every way to build a rectangle out of 12 squares is a fact about the number 12.' },
      { n: 19, strand: 'Ways of Counting', title: 'Only Two Rectangles', sub: 'Some numbers can only be built one way, and that turns out to matter.' },
      { n: 20, strand: 'Ways of Counting', title: 'Sharing Without Remainder', sub: 'Division asks two different questions, and they are not the same question.' },
      { n: 21, strand: 'Number Structure', title: 'What Is Left Over', sub: 'The leftovers are not a mistake. They repeat, and the repeating is useful.' },
      { n: 22, strand: 'Number Structure', title: 'The Days Wrap Around', sub: 'Thirty days from Monday. You can work it out without counting thirty days.' },
      { n: 23, strand: 'Data', title: 'Reading a Scaled Graph', sub: 'One square does not always mean one thing, and that is where mistakes live.' },
      { n: 24, strand: 'Data', title: 'Counting From a Picture', sub: 'Half a symbol is where nearly everybody gets it wrong.' },
      { n: 25, strand: 'Logic & Proof', title: 'Puzzle Fair', sub: 'A little of everything from Weeks 14 to 24. No new rules this week.' },
      { n: 26, strand: 'Fractions', title: 'Parts of a Whole', sub: 'Equal parts. The word equal is doing all the work in that sentence.' },
      { n: 27, strand: 'Ways of Counting', title: 'Making One Whole', sub: 'Counting, but with fraction pieces. Same job: list them in order, miss none.' },
      { n: 28, strand: 'Fractions', title: 'Same Amount, Different Name', sub: 'One half and three sixths are the same amount wearing different clothes.' },
      { n: 29, strand: 'Dots & Lines', title: 'Coloring a Schedule', sub: 'Five clubs, and some of them cannot meet at the same time.' },
      { n: 30, strand: 'Dots & Lines', title: 'Can Everyone Be Paired?', sub: 'Four students, four jobs. Sometimes it fits and sometimes nothing you try will.' },
      { n: 31, strand: 'Steps & Rules', title: 'Instructions With a Repeat', sub: 'The same four sides, written once instead of four times.' },
      { n: 32, strand: 'Steps & Rules', title: 'Instructions With a Question', sub: 'A program that looks at what is in front of it and decides.' },
      { n: 33, strand: 'Ways of Counting', title: 'Counting Paths on a Grid', sub: 'Every corner knows how many routes reach it, if you ask the two corners behind it.' },
      { n: 34, strand: 'Ways of Counting', title: 'The Triangle of Numbers', sub: 'The route numbers, tipped over. And the handshakes are hiding in it.' },
      { n: 35, strand: 'Logic & Proof', title: 'Prove It With Pairing', sub: 'Nine people, three handshakes each. It cannot happen, and here is why.' },
      { n: 36, strand: 'Ways of Counting', title: 'The Counting Book, Finished', sub: 'Thirty-six weeks of pages. This week you turn them into one book.' },
    ],
  },
  {
    slug: 'grade-4', grade: 4, title: 'It Cannot Be Done',
    move: 'Rule it out',
    moveLine: 'An invariant proves a thing impossible without checking every case.',
    artifact: 'The Proof File',
    artifactLine: 'One page per impossibility, each with the invariant that settles it and the student\'s own account of why no amount of trying would help.',
    lede: 'Some things are not merely hard. They cannot be done, and you can know it without trying every case. The year is built on invariants: find what a move cannot change, and the future is settled. Parity, coloring, degree and the Euler count each rule something out for good.',
    strands: ['Dots & Lines', 'Fractions', 'Logic & Proof', 'Number Structure', 'Shape & Space', 'Steps & Rules', 'Ways of Counting'],
    standards: ['4.G.3', '4.MD.2', '4.MD.5', '4.MD.7', '4.NBT.1', '4.NBT.2', '4.NBT.4', '4.NBT.5', '4.NF.1', '4.NF.2', '4.NF.5', '4.NF.6', '4.OA.3', '4.OA.4', '4.OA.5'],
    pages: 77, checks: 522,
    workbook: '/downloads/it-cannot-be-done-grade4.pdf',
    guide: '/downloads/it-cannot-be-done-grade4-teacher-guide.html',
    weeks: [
      { n: 1, strand: 'Logic & Proof', title: 'The Thing That Never Changes', sub: 'Find what a move cannot touch, and you can rule out the future.' },
      { n: 2, strand: 'Number Structure', title: 'Odd, Even and Impossible', sub: 'Odd and even is not a label. It is a tool that rules things out.' },
      { n: 3, strand: 'Number Structure', title: 'Factor Rectangles', sub: 'Every rectangle you can build from a number is a fact about that number.' },
      { n: 4, strand: 'Number Structure', title: 'Primes and Composites', sub: 'Cross out every number that is a multiple of something. Look at what survives.' },
      { n: 5, strand: 'Number Structure', title: 'Building From Primes', sub: 'Break a number apart however you like. The bottom of the tree is always the same.' },
      { n: 6, strand: 'Number Structure', title: 'Multiples That Meet', sub: 'Two rhythms started together. When do they line up again?' },
      { n: 7, strand: 'Number Structure', title: 'The Biggest Shared Factor', sub: 'The other end of last week. Not where they meet, but what they share.' },
      { n: 8, strand: 'Logic & Proof', title: 'Coloring Proves It', sub: 'Color the board first. The coloring does the arguing.' },
      { n: 9, strand: 'Logic & Proof', title: 'The Domino Problem', sub: 'Sixty-two squares, thirty-one dominoes, and it cannot be done.' },
      { n: 10, strand: 'Dots & Lines', title: 'Degree Tells You', sub: 'Add up every degree in any drawing at all. The answer is never odd.' },
      { n: 11, strand: 'Dots & Lines', title: 'Trace It or Prove You Cannot', sub: 'The old bridge puzzle, settled in one line, without walking anywhere.' },
      { n: 12, strand: 'Logic & Proof', title: 'Impossible Fair', sub: 'Six claims. Prove each one, or knock it down. You may not shrug.' },
      { n: 13, strand: 'Logic & Proof', title: 'Case Files', sub: 'Everything from the first twelve weeks, in one folder.' },
      { n: 14, strand: 'Number Structure', title: 'Divisible by 2, 5 and 10', sub: 'Why does only the last digit matter? There is a reason, and it is short.' },
      { n: 15, strand: 'Number Structure', title: 'Divisible by 3 and 9', sub: 'Add the digits. It is not a trick, and here is why it works.' },
      { n: 16, strand: 'Number Structure', title: 'Casting Out Nines', sub: 'A real check on multiplication, from the rule you proved last week.' },
      { n: 17, strand: 'Number Structure', title: 'Wrapping Around, Again', sub: 'Casting out nines was not a trick. It was arithmetic on a wheel.' },
      { n: 18, strand: 'Number Structure', title: 'The Day of the Week', sub: 'A whole year on a seven-wheel, and no counting on fingers.' },
      { n: 19, strand: 'Shape & Space', title: 'Lines of Symmetry', sub: 'Fold it. If the two halves land on each other, you found a line.' },
      { n: 20, strand: 'Shape & Space', title: 'Turning a Shape', sub: 'Fold lines are not the only kind of symmetry. Some shapes only turn.' },
      { n: 21, strand: 'Shape & Space', title: 'The Eight Ways to Move a Square', sub: 'Every move that leaves a square looking the same. There are exactly eight.' },
      { n: 22, strand: 'Shape & Space', title: 'Angles That Must Add Up', sub: 'Tear the three corners off any triangle at all. They make a straight line.' },
      { n: 23, strand: 'Shape & Space', title: 'Tiling the Floor', sub: 'Only three regular shapes tile a floor. The reason is one division.' },
      { n: 24, strand: 'Shape & Space', title: 'Impossible Tilings', sub: 'Two boards, one corner different, and the answers are not the same.' },
      { n: 25, strand: 'Logic & Proof', title: 'Puzzle Fair', sub: 'A little of everything from Weeks 14 to 24.' },
      { n: 26, strand: 'Ways of Counting', title: 'Choosing a Team', sub: 'Line them up, then divide out the orderings you did not want.' },
      { n: 27, strand: 'Ways of Counting', title: 'The Triangle Grows', sub: 'Every number is the two above it added together, and that rule builds the whole thing.' },
      { n: 28, strand: 'Ways of Counting', title: 'The Triangle and the Teams', sub: 'Last week\'s triangle and the week before\'s teams are the same numbers.' },
      { n: 29, strand: 'Dots & Lines', title: 'Trees', sub: 'Joined up, with no way round. Count the lines and you will find a rule.' },
      { n: 30, strand: 'Dots & Lines', title: 'The Cheapest Network', sub: 'Join every town for the least money. The answer is always a tree.' },
      { n: 31, strand: 'Steps & Rules', title: 'Two Ways to Multiply', sub: 'Two methods, the same answer, and a fair way to compare the work.' },
      { n: 32, strand: 'Steps & Rules', title: 'The Euclid Machine', sub: 'Take the smaller from the bigger, over and over. It always stops, and where it stops matters.' },
      { n: 33, strand: 'Fractions', title: 'The Same Point on the Line', sub: 'Equivalent fractions are not two things that are equal. They are one point with two names.' },
      { n: 34, strand: 'Fractions', title: 'Parts of a Hundred', sub: 'A hundred squares, and two ways to say the same shading.' },
      { n: 35, strand: 'Logic & Proof', title: 'The Weighing Puzzles', sub: 'How much can one weighing possibly tell you? Count before you weigh.' },
      { n: 36, strand: 'Logic & Proof', title: 'The Proof File, Finished', sub: 'Thirty-three pages of reasons. This week they become one folder.' },
    ],
  },
  {
    slug: 'grade-5', grade: 5, title: 'The Best Way',
    move: 'Cost it',
    moveLine: 'A method has a price in steps, and prices can be compared.',
    artifact: 'The Method Book',
    artifactLine: 'Every method the year meets, with what it costs, when it is the right choice, and the case where it is beaten.',
    lede: 'Two procedures can both give the right answer and still not be equally good. The year counts comparisons, races three sorting methods on the same cards, walks Dijkstra and Kruskal by hand, and finds the case where the greedy rule does the wrong thing.',
    strands: ['Dots & Lines', 'Fractions', 'Logic & Proof', 'Number Structure', 'Steps & Cost', 'Ways of Counting'],
    standards: ['5.G.1', '5.G.2', '5.MD.1', '5.MD.3', '5.MD.5', '5.NBT.1', '5.NBT.2', '5.NBT.5', '5.NBT.6', '5.NBT.7', '5.NF.4', '5.NF.6', '5.NF.7', '5.OA.1', '5.OA.3'],
    pages: 77, checks: 406,
    workbook: '/downloads/the-best-way-grade5.pdf',
    guide: '/downloads/the-best-way-grade5-teacher-guide.html',
    weeks: [
      { n: 1, strand: 'Steps & Cost', title: 'What Is a Step?', sub: 'Before you can say one method is better, you have to say what you are counting.' },
      { n: 2, strand: 'Steps & Cost', title: 'Two Sorts, Counted', sub: 'Two methods, the same cards, the same finish, and very different bills.' },
      { n: 3, strand: 'Steps & Cost', title: 'Sorting by Splitting', sub: 'Cut the pile in half, sort both halves, then zip them together.' },
      { n: 4, strand: 'Steps & Cost', title: 'Searching a Sorted List', sub: 'Halving is so much better than looking that the numbers stop feeling real.' },
      { n: 5, strand: 'Number Structure', title: 'Doubling and Halving', sub: 'The numbers behind last week. They get very big very fast.' },
      { n: 6, strand: 'Steps & Cost', title: 'The Greedy Rule', sub: 'Take the biggest that fits, then do it again. Simple, fast, and usually right.' },
      { n: 7, strand: 'Steps & Cost', title: 'When Greedy Fails', sub: 'Change three coins and the simple rule starts giving wrong answers.' },
      { n: 8, strand: 'Dots & Lines', title: 'Shortest Path With Costs', sub: 'Not the fewest roads. The cheapest total, in dollars and cents.' },
      { n: 9, strand: 'Dots & Lines', title: 'The Cheapest Network', sub: 'Two completely different methods. Same answer, every time.' },
      { n: 10, strand: 'Steps & Cost', title: 'Packing the Boxes', sub: 'Same parcels, same boxes. Change the order they arrive in and you need a whole extra box.' },
      { n: 11, strand: 'Steps & Cost', title: 'Scheduling the Jobs', sub: 'Six jobs, thirteen days of work, and it can all be done in ten.' },
      { n: 12, strand: 'Steps & Cost', title: 'Method Fair', sub: 'One problem, four methods, one bill each.' },
      { n: 13, strand: 'Logic & Proof', title: 'Case Files', sub: 'Everything from the first twelve weeks, priced.' },
      { n: 14, strand: 'Ways of Counting', title: 'Counting on a Grid', sub: 'Streets on a coordinate grid, and only two directions allowed.' },
      { n: 15, strand: 'Ways of Counting', title: 'Paths That Avoid a Block', sub: 'Count everything, then subtract the ones you did not want.' },
      { n: 16, strand: 'Ways of Counting', title: 'Two Circles, Then Three', sub: 'Add the three clubs and you have counted some children twice and some three times.' },
      { n: 17, strand: 'Ways of Counting', title: 'Counting the Leftovers', sub: 'Sometimes the fastest way to count what you want is to count what you do not.' },
      { n: 18, strand: 'Fractions', title: 'Sharing Fairly', sub: 'Dividing by a fraction is a counting question in disguise.' },
      { n: 19, strand: 'Fractions', title: 'A Fraction of a Fraction', sub: 'Cut a square one way, then the other. The overlap is the answer.' },
      { n: 20, strand: 'Number Structure', title: 'Powers and Place Value', sub: 'Every column is ten times the one on its right, and that is a rule you can push around.' },
      { n: 21, strand: 'Number Structure', title: 'Base Five', sub: 'A whole number system with only five digits. Not a code, a way of counting.' },
      { n: 22, strand: 'Number Structure', title: 'Carrying in Base Five', sub: 'Column addition works in any base. Only the moment you carry changes.' },
      { n: 23, strand: 'Steps & Cost', title: 'How a Machine Adds', sub: 'Two digits, one carry, and that is the entire arithmetic of a computer.' },
      { n: 24, strand: 'Steps & Cost', title: 'Logic Gates', sub: 'Three tiny machines. Wire them together and you get last week’s adding.' },
      { n: 25, strand: 'Logic & Proof', title: 'Puzzle Fair', sub: 'A little of everything from Weeks 14 to 24.' },
      { n: 26, strand: 'Dots & Lines', title: 'Flow Through a Network', sub: 'Water, not routes. How much can you push from one end to the other?' },
      { n: 27, strand: 'Dots & Lines', title: 'The Bottleneck', sub: 'The answer is never about the big pipes. It is about the narrow place.' },
      { n: 28, strand: 'Dots & Lines', title: 'Matching People to Jobs', sub: 'Greedy gets stuck. Then you fix it without starting over.' },
      { n: 29, strand: 'Dots & Lines', title: 'Coloring, and How Good Is Greedy?', sub: 'Six clubs, two slots are enough, and greedy uses three. The order is to blame.' },
      { n: 30, strand: 'Logic & Proof', title: 'A Lower Bound', sub: 'Two halves make an answer: a method that works, and a proof nothing beats it.' },
      { n: 31, strand: 'Ways of Counting', title: 'Rules That Look Back', sub: 'To count a strip of ten, count a strip of nine and a strip of eight.' },
      { n: 32, strand: 'Ways of Counting', title: 'A Rule From a Table', sub: 'Two patterns started together. One is always double the other, and you can see why.' },
      { n: 33, strand: 'Logic & Proof', title: 'Two Rules, One Answer', sub: 'A formula and a count that disagree cannot both be right, so check.' },
      { n: 34, strand: 'Steps & Cost', title: 'Sorting Really Big Lists', sub: 'At eight cards it hardly matters. At a thousand it decides whether the job is possible.' },
      { n: 35, strand: 'Steps & Cost', title: 'Which Method Would You Pay For?', sub: 'The last real week. A decision, with money on it.' },
      { n: 36, strand: 'Steps & Cost', title: 'The Method Book, Finished', sub: 'Thirty-three pages of methods, each with its price. This week it becomes one book.' },
    ],
  },
  {
    slug: 'grade-6', grade: 6, title: 'Find the Rule',
    move: 'Generalize it',
    moveLine: 'A pattern becomes a rule with a letter, and then the rule gets proved.',
    artifact: 'The Rule Book',
    artifactLine: 'Each rule stated in symbols, with the picture it came from and the argument that it holds for every n, not just the ones that were tried.',
    lede: 'One letter says what a hundred examples cannot. The year turns patterns into rules written with a variable, then insists the rule be justified: the same count derived two different ways, a formula checked against a case nobody drew.',
    strands: ['Data', 'Dots & Lines', 'Logic & Proof', 'Number Structure', 'Patterns & Rules', 'Ratio & Rate', 'Shape & Space', 'Ways of Counting'],
    standards: ['6.EE.2', '6.EE.3', '6.EE.4', '6.EE.5', '6.EE.6', '6.EE.9', '6.G.3', '6.G.4', '6.NS.4', '6.NS.6', '6.NS.7', '6.NS.8', '6.RP.1', '6.RP.2', '6.RP.3', '6.RP.3c', '6.SP.1', '6.SP.2', '6.SP.3', '6.SP.5', '6.SP.5c'],
    pages: 77, checks: 436,
    workbook: '/downloads/find-the-rule-grade6.pdf',
    guide: '/downloads/find-the-rule-grade6-teacher-guide.html',
    weeks: [
      { n: 1, strand: 'Patterns & Rules', title: 'A Letter For Any Number', sub: 'One letter says what a hundred examples cannot.' },
      { n: 2, strand: 'Patterns & Rules', title: 'A Pattern That Grows', sub: 'Draw the shape, count the dots, and let the picture hand you the formula.' },
      { n: 3, strand: 'Patterns & Rules', title: 'Triangular Numbers', sub: '1, 3, 6, 10, 15. You have met them three times already. Now you get the formula.' },
      { n: 4, strand: 'Ways of Counting', title: 'The Handshake Formula, Proved', sub: 'Grade 2 counted them. Grade 3 found the rule. This week you prove it.' },
      { n: 5, strand: 'Patterns & Rules', title: 'Adding One to n', sub: 'Pair the ends. The whole sum falls out in one line.' },
      { n: 6, strand: 'Patterns & Rules', title: 'The Odd Numbers Make a Square', sub: '1, then 1 + 3, then 1 + 3 + 5. The answers are square, and the picture says why.' },
      { n: 7, strand: 'Patterns & Rules', title: 'Looking Back or Jumping Ahead', sub: 'Two kinds of rule. One needs the answers before it, and one does not.' },
      { n: 8, strand: 'Logic & Proof', title: 'When a Pattern Lies', sub: '1, 2, 4, 8, 16. Everybody says 32. Everybody is wrong.' },
      { n: 9, strand: 'Logic & Proof', title: 'Proof by Picture', sub: 'Some arrangements settle a question before a single symbol is written.' },
      { n: 10, strand: 'Logic & Proof', title: 'Proof by Cases', sub: 'Split the question into a few kinds, settle each one, and you have settled them all.' },
      { n: 11, strand: 'Ways of Counting', title: 'Counting the Same Thing Twice', sub: 'Count one thing two ways. The two answers must be equal, so you have a rule for free.' },
      { n: 12, strand: 'Patterns & Rules', title: 'Rule Fair', sub: 'Six patterns. Find each rule, and say how sure you are.' },
      { n: 13, strand: 'Logic & Proof', title: 'Case Files', sub: 'Everything from the first twelve weeks, in one folder.' },
      { n: 14, strand: 'Ratio & Rate', title: 'Ratio as a Rule', sub: 'Three cups of flour to two of water. That is a rule with a letter hiding in it.' },
      { n: 15, strand: 'Ratio & Rate', title: 'One of Them', sub: 'Reduce everything to one, and any two things become comparable.' },
      { n: 16, strand: 'Ratio & Rate', title: 'Out of a Hundred', sub: 'Percent is a ratio wearing a uniform. Everything is out of a hundred.' },
      { n: 17, strand: 'Dots & Lines', title: 'Scaling a Network', sub: 'Every road doubles in price. What happens to the cheapest route?' },
      { n: 18, strand: 'Dots & Lines', title: 'Everyone Plays Everyone', sub: 'A round robin, counted with the handshake formula and read as ratios.' },
      { n: 19, strand: 'Number Structure', title: 'Factors, By Primes', sub: 'Grade 4 found common factors by listing. Primes make it a rule instead.' },
      { n: 20, strand: 'Number Structure', title: 'All Four Quadrants', sub: 'The grid goes left and down as well, and nothing else changes.' },
      { n: 21, strand: 'Shape & Space', title: 'Distance on a Grid', sub: 'A delivery van cannot go through buildings. Its distance is a different distance.' },
      { n: 22, strand: 'Shape & Space', title: 'A Square Circle', sub: 'A circle is every point the same distance from the middle. Change the distance, change ' },
      { n: 23, strand: 'Shape & Space', title: 'Nets and Solids', sub: 'Flatten a solid, count its parts, and put it back together.' },
      { n: 24, strand: 'Patterns & Rules', title: 'The Formula That Always Holds', sub: 'Faces, edges and corners. One little sum comes out the same for every solid you try.' },
      { n: 25, strand: 'Logic & Proof', title: 'Puzzle Fair', sub: 'A little of everything from Weeks 14 to 24.' },
      { n: 26, strand: 'Ways of Counting', title: 'n Choose k', sub: 'The counting you have done since Grade 3, finally written as a formula.' },
      { n: 27, strand: 'Ways of Counting', title: 'Patterns in the Triangle', sub: 'Every row, every diagonal and every sum in Pascal\'s triangle means something.' },
      { n: 28, strand: 'Ways of Counting', title: 'At Least One', sub: 'Three words that always mean the same instruction: count them all, count the ones with ' },
      { n: 29, strand: 'Ways of Counting', title: 'Three Circles, In Symbols', sub: 'Grade 5 filled the regions in. This week the picture becomes a formula.' },
      { n: 30, strand: 'Ratio & Rate', title: 'How Likely Is It?', sub: 'Chance is a ratio: the outcomes you want against all the outcomes there are.' },
      { n: 31, strand: 'Data', title: 'Data Has a Shape', sub: 'Nine numbers on a line. The shape says more than any single number can.' },
      { n: 32, strand: 'Data', title: 'Center and Spread', sub: 'One number for where the data sits, one for how far it wanders.' },
      { n: 33, strand: 'Data', title: 'Same Average, Different Story', sub: 'Two classes, one average, and you would not want to swap them.' },
      { n: 34, strand: 'Data', title: 'Finding the Middle', sub: 'The median needs the data sorted, and sorting has a price you already know.' },
      { n: 35, strand: 'Logic & Proof', title: 'Pigeonhole, Grown Up', sub: 'Grade 3 put marbles in boxes. Now the boxes are a city.' },
      { n: 36, strand: 'Patterns & Rules', title: 'The Rule Book, Finished', sub: 'Thirty-three pages of rules. This week they become one book, and the line ends.' },
    ],
  },
];

export function bookBySlug(slug: string): MathBook | undefined {
  return MATH_LINE.find((b) => b.slug === slug);
}

/** Every distinct standard code the line names, across every book. */
export const MATH_STANDARD_COUNT = 103;

/** "Grades 1 to 6". Derived, because the site said "Grades 2 to 6" in
 *  nine places and adding a book below Grade 2 would have missed some. */
export const MATH_GRADE_RANGE = 'Grades 1 to 6';

/** The moves in order, for the sentence the line page makes out of them. */
export const MATH_MOVES = MATH_LINE.map((b) => b.move.toLowerCase());

/** Weeks written across the line. */
export const MATH_WEEK_COUNT = MATH_LINE.reduce((n, b) => n + b.weeks.length, 0);

/** Guide answers recomputed from the problems, summed across the line. */
export const MATH_CHECK_COUNT = MATH_LINE.reduce((n, b) => n + b.checks, 0);
