/**
 * Totals across every published 36-week year.
 *
 * GENERATED by brand/mksite.py in the curriculum repository. Each number is
 * read off the PDF in public/downloads that a school actually receives, so
 * these describe what is published rather than what is written down
 * somewhere. Both of these were hand-typed once and both were wrong within a
 * month of a new book shipping.
 */

export const PUBLISHED_YEARS = [
  { label: 'Grade 2 mathematics', file: '/downloads/discrete-math-adventures-workbook.pdf', standards: 19 },
  { label: 'Grade 3 mathematics', file: '/downloads/count-every-way-grade3.pdf', standards: 18 },
  { label: 'Grade 4 mathematics', file: '/downloads/it-cannot-be-done-grade4.pdf', standards: 15 },
  { label: 'Grade 5 mathematics', file: '/downloads/the-best-way-grade5.pdf', standards: 15 },
  { label: 'Grade 6 mathematics', file: '/downloads/find-the-rule-grade6.pdf', standards: 21 },
  { label: 'Grade 4 entrepreneurship', file: '/downloads/venture-year-grade4.pdf', standards: 11 },
  { label: 'Grade 5 entrepreneurship', file: '/downloads/numbers-year-grade5.pdf', standards: 14 },
] as const;

/** 36 weeks each, so this is the count of published years times 36. */
export const PUBLISHED_WEEKS = PUBLISHED_YEARS.length * 36;

/**
 * Distinct CCSS-M codes named in the 'In class this week' line across every
 * published year. Books overlap: the per-book counts sum higher than this.
 */
export const PUBLISHED_STANDARDS = 98;
